### ISSUE TITLE
Improving Communication Channels for New Contributors

### ISSUE THREAD

**Issue by sliriano** [e-valuation/EvaP#1906] opened 2023-03-20 23:39 UTC
I recently came across the e-vap project as part of a school project, and I am excited about the potential to contribute. While exploring the repository, I noticed an area that could benefit from improvement: communication channels for new contributors.

As someone interested in contributing by translating the community documentation into different languages, I was surprised to find that language translations are not currently listed as an issue in the GitHub repository. Additionally, there is no clear list of contact information for maintainers or community members, which makes it difficult for potential contributors like myself to reach out and offer help.

To foster a more welcoming environment for new contributors, I'd like to suggest the following improvements:

Add a "Contributing" section to the README file or create a separate CONTRIBUTING.md file, outlining the steps for potential contributors to get started, including how to submit translation requests and other types of contributions.

Create and maintain a list of contact information for project maintainers and other key community members, either in the repository or on the project website. This will enable new contributors to get in touch with the appropriate people when they have questions or need guidance.

I believe that implementing these suggestions will make it easier for new contributors to join the e-vap project and contribute their skills and expertise. I hope you find these suggestions helpful.

**Comment by janno42** [comment] 2023-03-21 10:19
Hi and thanks for your message! We appreciate any helping hand and I'll gladly answer your aspects in detail below.

**Translating the community documentation**
I don't know if I understood correctly, but if you meant translating the readme or wiki content, this is not common for open source repositories and not something we want for our repository. All documentation, comments, etc. should be in English only.

**Language translations are not currently listed as an issue**
If you mean translations of the application, you are correct. EvaP uses Django's internationalization features to be translatable and is currently available in English and German. All translations from the original English user-facing texts are done entirely by me during the release process to ensure consistency of wording and phrasing. So during development, all texts will be written in English, marked as translatable, and that's it for this part. We don't have any issues for open translation tasks by design.

**There is no clear list of contact information for maintainers or community members**
There is no specific contact list, but there is the standard GitHub list of contributors and it should be possible to find the current main contributors there. It is also possible to open issues or pull requests just like you did. Are there other ways of communication  you would need to contribute?

**Add a "Contributing" section to the README file or create a separate CONTRIBUTING.md file**
There already is a "Contributing" section in the readme file. Can you tell us what specific information would have helped you? There is certainly room for some helpful points here and there that we can add!

**Comment by He3lixxx** [comment] 2023-03-21 10:43
I can see how finding contact information for maintainers is a bit tricky. We could add a link to https://github.com/orgs/e-valuation/people to the readme's "Contributing" section. (To get the email addresses, you'd still have to explicitly go to the user profiles, though).

**Comment by He3lixxx** [comment] 2023-04-03 20:12
@sliriano I'm not really sure how we should proceed here. What are specific changes you would like to see implemented?

**Comment by He3lixxx** [comment] 2023-04-17 16:42
Closing for now. Feel free to re-open (or just open a pull request) if there's specific changes you'd like to see implemented.

**Closed by He3lixxx** 2023-04-17 16:42 UTC
