### ISSUE TITLE
Adding an editor disables preselected (and disabled) checkboxes 

### ISSUE THREAD

**Issue by MrSerth** [e-valuation/EvaP#1482] opened 2020-06-09 12:09 UTC
As an editor, I would like to add another editor without changing other parts of the questionnaire. I would expect that other parts of the page remain unchanged and adding is performed.

However, when adding an editor, the preselected list of questionnaires gets emptied.

Expected / Previously selected:
![Bildschirmfoto 2020-06-09 um 14 06 03](https://user-images.githubusercontent.com/7300329/84145738-bcd3d800-aa5a-11ea-9c67-ca4d8fb46202.png)

After adding a contributor:
![Bildschirmfoto 2020-06-09 um 14 08 32](https://user-images.githubusercontent.com/7300329/84145745-bf363200-aa5a-11ea-852a-1c9c6ee9bf99.png)

**Comment by janno42** [comment] 2020-06-09 12:12
duplicate of #1479

**Closed by janno42** 2020-06-09 12:12 UTC
